export const API_URL: string | undefined = process.env.REACT_APP_API_URL
// export const apiKey = '4fc7b001e8a107fe1fddc6b41ed0f4af'
export const API_KEY: string = '8ee18f65008b7108b46834a1a60f55fc'
export const LANG: string = 'fr-fr'
export const IMAGE_URL: string | undefined = process.env.REACT_APP_IMAGE_URL
// export const imagePathOriginal = `${imagePath}/original`
// export const imagePath400 = `${imagePath}/w400`
export const TYPE_TV: string = 'tv'
export const TYPE_MOVIE: string = 'movie'